# Generated by Django 4.0.1 on 2023-07-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0003_alter_patientmodel_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clinic', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=500)),
                ('experience', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('avail_timing', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
